### ISSUE TITLE
Cannot post error

### ISSUE THREAD

**Issue by GaryFurash** [helton/bitbucket-snippet#1]
```
error:
 { [Error: cannot POST /site/oauth2/access_token (400)]
   status: 400,
   text: '{"error_description": "Invalid resource owner username/password", "error": "invalid_request"}',
   method: 'POST',
   path: '/site/oauth2/access_token' },
```

I think my user id and password is right.

**Comment by helton** [comment]
Hi @GaryFurash ,

I just tried with the current version and it worked fine to me.
My steps after I installed a fresh version:
`> snippet hello.py`
I typed my username and password and I got:
`Snippet created: https://bitbucket.org/snippets/h3170n/GpXx6`

Can you try it again, please?
Make sure that you can access your Bitbucket account with the information provided.
